select *
from PROD_DW.DW.ACCOUNTING_TELESALES_COMMISSION_REPORT
    limit 10;


--SUBSCRIPTION_FACT_SVIEW table - can be frozen FIN_MET_FROZEN.ARCHIVE_2021_12.FACT_BASE_SUBSCRIPTION_FACT_SVIEW or live PROD_DW.FACT_BASE.SUBSCRIPTION_FACT_SVIEW
select *
from PROD_DW.FACT_BASE.SUBSCRIPTION_FACT_SVIEW
where snaid='SAC0000662082'
and IS_CURRENT_VERSION=1;



--SUBSCRIPTION_DATES - can be frozen FIN_MET_FROZEN.ARCHIVE_2021_12.subscription_dates  or LIVE: FIN_MET_LIVE.DERIVED.subscription_dates
select *
from FIN_MET_FROZEN.ARCHIVE_2021_12.subscription_dates
where snaid='SAC0000662082';